### ISSUE TITLE
Calculate Fu's Fs p-value.

### ISSUE THREAD

**Issue by EricArcher** [EricArcher/strataG#8]
For function fusFs. Requires incorporating coalescent simulation (use [coala](https://github.com/statgenlmu/coala) or [scrm](https://github.com/scrm/scrm) package?).

**Comment by chlarose** [comment]
Hi, I have this request as well. It would be very useful to get a p-value in addition of the Fu's Fs value, better to complete the statistics in a paper (as I am trying to do now). I would then prefer to use/cite your R package for the whole set of analysis instead of several softwares, if possible.
Best,
Chloé

**Comment by EricArcher** [comment]
After reading through Fu 1997 again, my understanding is that to best calculate a p-value, a simulation should be constructed to create a null distribution. Because this is case-specific, it isn't clear to me how to automatically implement it in the function. However, `strataG` has a powerful wrapper for `fastsimcoal2` that can be easily used to construct a simulation to obtain p-values from. See `?strataG::fscWrite()`, `?strataG::fscRun()`, and `fscTutorial()`.
